var array_items = [ // fixme: move to external database
	{product_name: 'foo',
	 unit_price: 1.23,
	 unit_dimension: '%',
	 units_in_stock: 4,
	 discontinued: true},

	{product_name: 'bar',
	 unit_price: 5.67,
	 unit_dimension: '%',
	 units_in_stock: 8,
	 discontinued: true},

	{product_name: 'baz',
	 unit_price: 9.10,
	 unit_dimension: 'руб.',
	 units_in_stock: 1,
	 discontinued: true},

	{product_name: 'qux',
	 unit_price: 1.12,
	 unit_dimension: '%',
	 units_in_stock: 1,
	 discontinued: true},

	{product_name: 'quux',
	 unit_price: 3.14,
	 unit_dimension: '$',
	 units_in_stock: 1,
	 discontinued: true},

	{product_name: 'quuz',
	 unit_price: 5.16,
	 unit_dimension: '%',
	 units_in_stock: 1,
	 discontinued: true},

	{product_name: 'corge',
	 unit_price: 7.18,
	 unit_dimension: '%',
	 units_in_stock: 1,
	 discontinued: false},

	{product_name: 'grault',
	 unit_price: 9.20,
	 unit_dimension: '%',
	 units_in_stock: 1,
	 discontinued: false},

	{product_name: 'garply',
	 unit_price: 1.22,
	 unit_dimension: '%',
	 units_in_stock: 2,
	 discontinued: false},

	{product_name: 'waldo',
	 unit_price: 3.24,
	 unit_dimension: '%',
	 units_in_stock: 2,
	 discontinued: true},

	{product_name: 'fred',
	 unit_price: 5.26,
	 unit_dimension: '%',
	 units_in_stock: 2,
	 discontinued: true},

	{product_name: 'plugh',
	 unit_price: 7.28,
	 unit_dimension: '%',
	 units_in_stock: 2,
	 discontinued: true},

	{product_name: 'xyzzy',
	 unit_price: 9.30,
	 unit_dimension: '%',
	 units_in_stock: 3,
	 discontinued: false},

	{product_name: 'thud',
	 unit_price: 1.32,
	 unit_dimension: '%',
	 units_in_stock: 3,
	 discontinued: false},
];
